### ISSUE TITLE
OTF Files 1.2 Wrong Font

### ISSUE THREAD

**Issue by fiercedeity-productions** [indestructible-type/Bodoni#10]
It seems as if the OpenType font files for version 1.2 are the wrong font. The TrueType files have no problem.
![image](https://user-images.githubusercontent.com/31538456/52163787-6c6a9e80-26df-11e9-8632-b5966ce7b3f9.png)
Typing text in notepad yields a font similar to Jost/Renner:
![image](https://user-images.githubusercontent.com/31538456/52163800-8ad09a00-26df-11e9-8e25-bbbc34af43e5.png)
This is true for all the OpenType font files:
![image](https://user-images.githubusercontent.com/31538456/52163805-991eb600-26df-11e9-8305-ed644d9d3f5f.png)
Perhaps the wrong files were copied over during distribution?

**Comment by fiercedeity-productions** [comment]
This confusion in OTF fonts is exhibited both in the GitHub repository and the download link on the website.

**Comment by thiagovscoelho** [comment]
Huh, I hadn’t tried testing in Notepad! I was trying the OTFs in Word, and the behavior was that they were invisible, as documented extensively in Issue #9. 
I also see another font entirely when viewing them in Notepad, but it looks nothing like Renner*. It seems to be a different font for every style and weight, but all the Fatface ones look like Lovelo Black:
![explorer_2019-02-02_18-59-01](https://user-images.githubusercontent.com/47187428/52169278-b1f98c80-271c-11e9-8a67-2edb8af3c749.png)
I believe if our issues are similar, we are simply seeing other fonts we have installed in place of Bodoni*. A lot of mine look like HK Grotesk.

**Comment by thiagovscoelho** [comment]
I don’t know this, but I think it is the same rot in the OTFs which is behind Issues #9 and #10. In Notepad, it probably simply displays another font because the OTFs, as far as it knows, have nothing to show for themselves. This is made evident by the Windows font preview, which in my computer also looks something like an obliqued Helvetica. Really, the fact that it works so well in LibreOffice Writer should be seen as the real exception here.

**Comment by EwonRael** [comment]
I have reviewed everything on my end and cannot find anything off, nor can I recreate this problem.

There isn't a way I could have mixed up the font files during distribution. If I had done that the fonts wouldn't be named Bodoni*, but rather whatever it was I mixed up.

The reason I have been using libre office to check things is because I have a linux machine. It's useful because of its out-dated approach to handling fonts. I could recreate the issues with style links, when that was a problem. 

Recreating problems is necessary for me to troubleshoot. I can't recreate this issue. I have tried everything that I can think of to fix it. 

I even tried to recreate the problem on my partners windows machine, but have had zero issues with the font, even in word or notepad.

**Comment by thiagovscoelho** [comment]
Are you sure you tried the latest OTFs? The TTFs look fine.
![2019-02-02_22-11-32](https://user-images.githubusercontent.com/47187428/52170764-8d5ede00-2737-11e9-895e-5d8645668c83.png)
Issue replicated to a tee in Windows 10 laptop on Notepad. Tests in Word did not replicate as well, as I will document in Issue #9.

**Comment by thiagovscoelho** [comment]
Note that normally, inside the box labeled “Exemplo” on my screenshots, Notepad shows a preview of the letters AaBbYyZz in the selected font. The fact that it doesn’t show Renner* or anything in that preview box in my previous two screenshots proves that there is in fact no “wrong font” in the font files, but that Renner* merely appears as a replacement because Notepad thinks there’s nothing to see in those OTFs.
![chrome_2019-02-03_13-51-54](https://user-images.githubusercontent.com/47187428/52178903-e2900380-27ba-11e9-9b0b-8f7387e4ed7f.png)

**Comment by fiercedeity-productions** [comment]
@EwonRael Are you sure you didn't include the wrong OTF files in the release? Try downloading one of the OTFs from the public repository, or from the website, and installing it. This was not a problem in version 1.1 – I still have the OTFs and they work perfectly, even in word. Alternatively you could list out the glyphs using [this online Font Inspector](fi.littlebigcrafter.com).

**Comment by fiercedeity-productions** [comment]
@EwonRael I would like to echo that this was not an issue with version 1.1 of the font, which can still be accessed through the repository's commit history.

**Comment by fiercedeity-productions** [comment]
Its nearly fixed! The problems are gone for most of the files, except for:
1. ```Bodoni-11-Bold.otf```
1. ```Bodoni-11-Bold-Italic.otf```
1. ```Bodoni-11-Book.otf```
1. ```Bodoni-11-Book-Italic.otf```

These _specific_ fonts work to an extent – they are usable in Notepad and Word, but:
1. ligatures do not work and
1. the Windows font preview is still confused

For example, here's Bodoni* 11 Book:
![image](https://user-images.githubusercontent.com/31538456/52194207-ccca1f00-284a-11e9-83ce-859535ced3f3.png)
![image](https://user-images.githubusercontent.com/31538456/52194219-dd7a9500-284a-11e9-9ba0-e84f1dd460ec.png)

All of the other font files work perfectly. Well done!

**Comment by EwonRael** [comment]
Are there still issues with the ligatures? Or are those working with the .otf files now?

**Comment by thiagovscoelho** [comment]
I don’t think Notepad has ever had ligature support. They are working fine on Word on the OTFs.

**Comment by EwonRael** [comment]
Okay I that's good enough for me.
Although, my experience with the current version of the ttf files is that notepad supports their ligatures and Microsoft word doesn't.

**Comment by Alice196498** [comment]
Notepad ſupports ligatures in the liga table, but not dlig or hiſt. I don’t have any experience with MS Word, but I have read that it can be weird.

**Comment by thiagovscoelho** [comment]
Yeah, Notepad does have ligatures on by default, this was my mistake. Weird how it would have just this one OpenType feature and not others, but good for readability.

**Comment by thiagovscoelho** [comment]
The TTF ligatures did work for me in Word 2016, they only didn’t work in Word 2010. Since you seem to have a new version of Word, it is weird to me that they wouldn’t work. Did you make sure to turn on the ligatures in the Font menu?

**Comment by thiagovscoelho** [comment]
![explorer_2019-02-04_17-12-10](https://user-images.githubusercontent.com/47187428/52231042-08430880-28a0-11e9-82af-0c2d1e9e3dfb.png)
The new OTFs no longer have this issue for me. You should try them, fiercedeity-productions!
