### ISSUE TITLE
Angle of Acute and Grave accents unnaturally ſteep.

### ISSUE THREAD

**Issue by Alice196498** [indestructible-type/Bodoni#17]
As per the title, it ſeems to me that the angles of the Acute and Grave accents are much ſteeper than would be natural, being quite nearly 90°. In my experience, it is more general that they have a much more gentle angle, which lends itſelf to eaſier reading and recognition of the characters. An example of ſome Bodoni founts printed on the Linotype can be ſeen [here](https://www.loc.gov/resource/dcmsiabooks.specimensoftypef00unit/?sp=31) ſhewing a more natural form of the accents.

**Comment by jeanm** [comment]
I don't know if there have been changes since this issue was opened. I personally find the current version of acute and grave accents to be very hard to read, as they are _not steep enough_ – the bottom part of the diacritic being essentially flat, or possibly even sloping down:
<img width="591" alt="Screenshot 2020-02-10 at 16 44 08" src="https://user-images.githubusercontent.com/107696/74203486-a50f5300-4c24-11ea-8808-6db4000d7501.png">

I quite like the examples given by @Alice196498 above, with the accents roughly at a 45° angle:
<img width="388" alt="Screenshot 2020-02-10 at 16 47 50" src="https://user-images.githubusercontent.com/107696/74203645-2b2b9980-4c25-11ea-8a7f-3ab3fa44a570.png">

**Comment by EwonRael** [comment]
yeah the photo @jeanm posted looks right to me... I agree that I like the look of the 45°. Can you post a screenshot @Alice196498 ?

**Comment by Alice196498** [comment]
Here’s a ſcreenſhot ſhewing the 12 point type as printed :
![default](https://user-images.githubusercontent.com/30258857/74244602-09b1d700-4d25-11ea-9569-21c38d1e9035.jpg)

**Comment by EwonRael** [comment]
No no I can see that just fine, what I'm wondering is what *my* font looks like to you. I agree with @jeanm that they don't look steep enough to me. Does yours look different or are we talking about the same thing using different language?

**Comment by Alice196498** [comment]
We’re talking about the ſame thing uſing different language. To me, the accents are quite nearly lying flat atop the letters, as in @jeanm’s firſt image above.

**Comment by EwonRael** [comment]
Cool. I'll get on this

**Comment by EwonRael** [comment]
Thank you guys so much for this kind of feedback. I have revamped the accent marks in the latest release, but I couldn't have done it without this feedback. Very useful the reference images and discussion.
