### ISSUE TITLE
Small visual glitch in lowercase italic k

### ISSUE THREAD

**Issue by mwsundberg** [indestructible-type/Bodoni#20]
With weight 600, optical size 88 lowercase italic settings there is a small nub in the upper left of the lowercase italic 'k'. 

![image](https://user-images.githubusercontent.com/5696404/76112768-dd4e4b00-5fb0-11ea-9941-9ca90be6af3d.png)

**Comment by EwonRael** [comment]
looks a bit screwy!

Some of this is the result of pushing variable fonts to their limit. Some of it has to do with the underlying geometry and can be improved. Some of it is the failures of whatever program is rendering this.

The best I can offer is that I'm going to be rexaming the geometry to see if I can get it to interpolate better, but that's going to be a long term project because it will be an overhaul of most of the glyphs. And I can't grantee that that will fix whatever is causing this.

**Comment by mwsundberg** [comment]
Sounds good, just passing along a discovery. That was on Adobe Illustrator CC, 24 I think at the time.

**Comment by EwonRael** [comment]
Hello!

I just made some changes to the underlying geometry in the italic k. Can you do me a favour and see if this is still creating rendering issues in Illustrator?

Thanks!

**Comment by mwsundberg** [comment]
All fixed! Thank you so much!

![image](https://user-images.githubusercontent.com/5696404/81345357-4ff9a680-9086-11ea-85c6-d0e979fb5707.png)
