### ISSUE TITLE
No style links

### ISSUE THREAD

**Issue by thiagovscoelho** [indestructible-type/Bodoni#3]
![winword_2019-01-30_14-55-23](https://user-images.githubusercontent.com/47187428/51998056-14ddf000-249f-11e9-81b7-2682c3624153.png)
Rather than seeing the fonts like this on the font menu, I would like to see only the roman versions, and have the bolds and italics accessible only by pressing the bold and italic software buttons. This is necessary in order to properly change a font in an old document to Bodoni* without laborious find-and-replace jobs for every style.

**Comment by EwonRael** [comment]
Ahh!

This is very reasonable and not supposed to happen! 

This kind of thing happens because every program seems to respect different metadata.

I don't want this to happen, and I can go on and on about why I think this might be, but in some ways that's not important.

What is important is that I want the style links too. I attempted to do that. That didn't happen. I'm going to try and fix it in the next release. This kind of thing never goes away. Metadata is a weird Hydra. Thanks for bringing this to my attention.

**Comment by EwonRael** [comment]
I just released version 1.2 which fixes metata and this should be solved!

I have tested it in libre office writer and it appears to have been resolved.

Thank you for bringing this to my attention.
